default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  
  # Important configs for cloud9, change password value
  # to what you entered in the previous psql step.
  template: template0
  username: ubuntu
  password: ''
  

development:
  <<: *default
  database: JientPorfolio_development

test:
  <<: *default
  database: JientPorfolio_test

production:
  <<: *default
  database: JientPorfolio_production
  username: JientPorfolio
  password: <%= ENV['JIENTPORFOLIO_DATABASE_PASSWORD'] %>
